/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tcs.pk.wrapper;

public class IDemandsCB {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IDemandsCB(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IDemandsCB obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tpkJniJNI.delete_IDemandsCB(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    tpkJniJNI.IDemandsCB_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    tpkJniJNI.IDemandsCB_change_ownership(this, swigCPtr, true);
  }

  public void newDemands(double mAz, double mEl, double eAz, double eEl, double m3R, double m3T) {
    if (getClass() == IDemandsCB.class) tpkJniJNI.IDemandsCB_newDemands(swigCPtr, this, mAz, mEl, eAz, eEl, m3R, m3T); else tpkJniJNI.IDemandsCB_newDemandsSwigExplicitIDemandsCB(swigCPtr, this, mAz, mEl, eAz, eEl, m3R, m3T);
  }

  public IDemandsCB() {
    this(tpkJniJNI.new_IDemandsCB(), true);
    tpkJniJNI.IDemandsCB_director_connect(this, swigCPtr, true, true);
  }

}
