/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package tcs.pk.wrapper;

public class tpkJniJNI {
  public final static native long new_TpkC();
  public final static native void delete_TpkC(long jarg1);
  public final static native void TpkC_init(long jarg1, TpkC jarg1_);
  public final static native void TpkC_newDemands(long jarg1, TpkC jarg1_, double jarg2, double jarg3, double jarg4, double jarg5, double jarg6, double jarg7);
  public final static native void TpkC_newTarget(long jarg1, TpkC jarg1_, double jarg2, double jarg3);
  public final static native void TpkC_offset(long jarg1, TpkC jarg1_, double jarg2, double jarg3);
}
